# -*- coding: utf-8 -*-
"""circuitAnalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDRbv5xSMXYB7NRo-ucuFt6WvavidFqo
"""

═
!pip install qiskit qiskit-aer matplotlib networkx seaborn scipy -q
print("✅ Dependencies installed")

import time
import re
import warnings
from collections import Counter, defaultdict

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.colors as mcolors
import seaborn as sns
import networkx as nx

from google.colab import files          # ← Colab file-upload widget
from qiskit import qasm2                # ← modern QASM loader (Qiskit 1.x)
from qiskit.converters import circuit_to_dag

warnings.filterwarnings("ignore")

# ── global plot style ──────────────────────────────────────────────────────
plt.rcParams.update({
    "figure.dpi": 120,
    "font.size": 11,
    "axes.titlesize": 13,
    "axes.labelsize": 11,
    "axes.grid": True,
    "grid.alpha": 0.25,
    "figure.facecolor": "white",
})

PAL = {
    "blue":   "#4C72B0",
    "orange": "#DD8452",
    "green":  "#55A868",
    "red":    "#C44E52",
    "purple": "#8172B2",
    "teal":   "#64B5CD",
}

PI = np.pi

def parse_angle(expr: str) -> float | None:
    """Evaluate a QASM angle expression (may contain 'pi')."""
    try:
        return float(expr.replace("pi", str(PI)))
    except ValueError:
        try:
            return eval(expr.replace("pi", str(PI)),
                        {"__builtins__": {}}, {"pi": PI})
        except Exception:
            return None

def is_clifford(a: float, tol: float = 1e-5) -> bool:
    """True iff angle is a multiple of π/2."""
    cliff = {0, PI/2, PI, 3*PI/2, 2*PI, -PI/2, -PI, -3*PI/2}
    return any(abs(a % (2*PI) - v % (2*PI)) < tol for v in cliff)

def fast_light_cone(qc, qmap: dict, target: int) -> set:
    """Backward light cone of `target` qubit."""
    affected = {target}
    for gate in reversed(qc.data):
        gate_q = {qmap[q] for q in gate.qubits}
        if affected & gate_q:
            affected |= gate_q
    return affected

def kpi_box(ax, value, label, sub="", color="#58a6ff"):
    """Dark-theme KPI card for the dashboard."""
    ax.set_facecolor("#161b22")
    ax.text(0.5, 0.58, str(value), ha="center", va="center",
            fontsize=20, fontweight="bold", color=color,
            transform=ax.transAxes)
    ax.text(0.5, 0.28, label, ha="center", va="center",
            fontsize=9, color="white", transform=ax.transAxes,
            fontweight="semibold")
    if sub:
        ax.text(0.5, 0.10, sub, ha="center", va="center",
                fontsize=7.5, color="#8b949e", transform=ax.transAxes)
    ax.set_xticks([]); ax.set_yticks([])
    for sp in ax.spines.values():
        sp.set_color(color); sp.set_linewidth(1.8)

def run_analysis():

    uploaded = files.upload()
    if not uploaded:

        return
    qasm_path = list(uploaded.keys())[0]
    t0 = time.time()


    print(f"\n[1/9] Loading circuit from '{qasm_path}' …")
    qc = qasm2.load(
        qasm_path,
        custom_instructions=qasm2.LEGACY_CUSTOM_INSTRUCTIONS,
    )
    qasm_string = qasm2.dumps(qc)
    dag         = circuit_to_dag(qc)
    num_qubits  = qc.num_qubits
    print(f"      ✅  {num_qubits} qubits loaded in {time.time()-t0:.1f}s")


    print("[2/9] Computing basic statistics …")
    count_ops  = qc.count_ops()
    total_g    = sum(count_ops.values())
    cx_count   = count_ops.get("cx",   0)
    swap_count = count_ops.get("swap", 0)
    raw_2q     = cx_count + swap_count
    single_q   = total_g - raw_2q
    cnot_equiv = cx_count + swap_count * 3

    qmap        = {q: qc.find_bit(q).index for gate in qc.data for q in gate.qubits}
    frontier    = defaultdict(int)
    layer_tot   = defaultdict(int)
    layer_2q    = defaultdict(int)
    layer_1q    = defaultdict(int)

    for node in dag.topological_op_nodes():
        qi    = [qmap[q] for q in node.qargs]
        layer = max((frontier[q] for q in qi), default=0) + 1
        for q in qi:
            frontier[q] = layer
        layer_tot[layer] += 1
        (layer_2q if len(qi) == 2 else layer_1q)[layer] += 1

    layers      = sorted(layer_tot.keys())
    depth       = len(layers)
    g_tot       = [layer_tot[l] for l in layers]
    g_2q        = [layer_2q[l]  for l in layers]
    g_1q        = [layer_1q[l]  for l in layers]
    two_q_depth = sum(1 for x in g_2q if x > 0)
    gate_density = total_g / (num_qubits * depth)

    print(f"      ✅  depth={depth}, gates={total_g}, 2Q-depth={two_q_depth}")


    print("[3/9] Analysing qubit connectivity …")
    interact = Counter()
    pairs_2q = []
    for gate in qc.data:
        if len(gate.qubits) == 2:
            q0, q1 = qmap[gate.qubits[0]], qmap[gate.qubits[1]]
            interact[tuple(sorted([q0, q1]))] += 1
            pairs_2q.append((q0, q1))

    G = nx.Graph()
    G.add_nodes_from(range(num_qubits))
    for (q0, q1), w in interact.items():
        G.add_edge(q0, q1, weight=w)

    degrees    = dict(G.degree())
    max_deg    = max(degrees.values())
    avg_deg    = np.mean(list(degrees.values()))
    diameter   = nx.diameter(G) if nx.is_connected(G) else None
    clustering = nx.average_clustering(G)
    g_density  = nx.density(G)


    print("[4/9] Parsing rotation angles …")
    angle_re = re.compile(r"(?:rx|ry|rz|u1|p)\(([^)]+)\)")
    raw_ang  = [parse_angle(m.group(1))
                for m in angle_re.finditer(qasm_string)
                if parse_angle(m.group(1)) is not None]
    angles      = np.array(raw_ang)
    non_cliff   = [a for a in angles if not is_clifford(a)]
    nc_frac     = len(non_cliff) / max(len(angles), 1)
    cliff_count = len(angles) - len(non_cliff)
    print("[5/9] Computing per-qubit gate load …")
    q_total = Counter()
    q_2q    = Counter()
    for gate in qc.data:
        for q in gate.qubits:
            idx = qmap[q]
            q_total[idx] += 1
            if len(gate.qubits) == 2:
                q_2q[idx] += 1
    g_load  = [q_total.get(q, 0) for q in range(num_qubits)]
    tq_load = [q_2q.get(q, 0)    for q in range(num_qubits)]


    print("[6/9] Computing backward light cones …")
    cone_sizes = []
    for q in range(num_qubits):
        cone_sizes.append(len(fast_light_cone(qc, qmap, q)))
    avg_cone = np.mean(cone_sizes)


    print("[7/9] Bipartition entanglement sweep …")
    cross_counts = []
    for cut in range(1, num_qubits):
        left  = set(range(cut))
        cross = sum(1 for (q0, q1) in pairs_2q if (q0 in left) != (q1 in left))
        cross_counts.append(cross)
    mid         = num_qubits // 2
    cen_cross   = cross_counts[mid - 1]
    ent_ub      = min(cen_cross, mid) * np.log(2)
    richness    = cen_cross / max(min(mid, num_qubits - mid), 1)


    print("[8/9] Generating figures …")


    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    fig.suptitle(f"Gate Distribution  ·  {qasm_path}", fontweight="bold")
    gates_list  = list(count_ops.keys())
    counts_list = list(count_ops.values())
    colors = list(PAL.values())[:len(gates_list)]
    wp = {"edgecolor": "white", "linewidth": 1.5}
    axes[0].pie(counts_list, labels=gates_list, autopct="%1.1f%%",
                colors=colors, startangle=140, wedgeprops=wp)
    axes[0].set_title("Proportions")
    bh = axes[1].barh(gates_list, counts_list, color=colors, edgecolor="white")
    axes[1].set_xlabel("Count"); axes[1].set_title("Counts")
    for bar, cnt in zip(bh, counts_list):
        axes[1].text(cnt + max(counts_list)*0.01,
                     bar.get_y() + bar.get_height()/2,
                     str(cnt), va="center", fontsize=9)
    axes[1].invert_yaxis()
    plt.tight_layout()
    plt.savefig("fig1_gate_distribution.png", bbox_inches="tight")
    plt.show()

    # --- Fig 2 · connectivity graph ----------------------------------------
    fig, axes = plt.subplots(1, 2, figsize=(16, 7))
    fig.suptitle("Qubit Interaction Graph", fontweight="bold")
    ew      = [G[u][v]["weight"] for u, v in G.edges()]
    max_w   = max(ew) if ew else 1
    nc      = [degrees.get(n, 0) for n in G.nodes()]
    ns      = [120 + 160*degrees.get(n, 0) for n in G.nodes()]
    norm_c  = mcolors.Normalize(vmin=0, vmax=max_deg)
    for ax_i, (pos_fn, title) in enumerate([
            (lambda: nx.circular_layout(G),        "Circular layout"),
            (lambda: nx.spring_layout(G, seed=42), "Spring layout"),
    ]):
        pos = pos_fn()
        nx.draw_networkx_nodes(G, pos, ax=axes[ax_i], node_size=ns,
                               node_color=nc, cmap=plt.cm.YlOrRd,
                               vmin=0, vmax=max_deg, alpha=0.9)
        nx.draw_networkx_edges(G, pos, ax=axes[ax_i],
                               edge_color=[w/max_w for w in ew],
                               edge_cmap=plt.cm.Blues,
                               width=[0.8+3.0*w/max_w for w in ew], alpha=0.7)
        nx.draw_networkx_labels(G, pos, ax=axes[ax_i],
                                font_size=7, font_color="black")
        axes[ax_i].set_title(title); axes[ax_i].axis("off")
    sm = plt.cm.ScalarMappable(cmap=plt.cm.YlOrRd, norm=norm_c)
    plt.colorbar(sm, ax=axes[1], label="Qubit degree", shrink=0.75)
    plt.tight_layout()
    plt.savefig("fig2_connectivity.png", bbox_inches="tight"); plt.show()

    # --- Fig 3 · interaction heatmap ----------------------------------------
    adj = np.zeros((num_qubits, num_qubits))
    for (q0, q1), cnt in interact.items():
        adj[q0, q1] = adj[q1, q0] = cnt
    fig, ax = plt.subplots(figsize=(12, 10))
    sns.heatmap(adj, ax=ax, cmap="YlOrRd", square=True,
                linewidths=0.2, linecolor="#e0e0e0",
                xticklabels=range(num_qubits),
                yticklabels=range(num_qubits),
                cbar_kws={"label": "Interaction count"})
    ax.set_title("Qubit Interaction Heatmap", fontweight="bold")
    ax.tick_params(labelsize=7)
    plt.tight_layout()
    plt.savefig("fig3_heatmap.png", bbox_inches="tight"); plt.show()

    # --- Fig 4 · depth profile -----------------------------------------------
    fig, axes = plt.subplots(2, 1, figsize=(15, 8), sharex=True)
    fig.suptitle("Circuit Depth Profile", fontweight="bold")
    axes[0].bar(layers, g_1q, color=PAL["blue"],  alpha=0.85, label="1Q gates")
    axes[0].bar(layers, g_2q, bottom=g_1q, color=PAL["red"], alpha=0.85, label="2Q gates")
    axes[0].set_ylabel("Gates per layer"); axes[0].legend()
    axes[0].set_title("Stacked Gate Count per Layer")
    cumul = np.cumsum(g_tot)
    axes[1].plot(layers, cumul, color=PAL["green"], lw=1.5)
    axes[1].fill_between(layers, cumul, alpha=0.25, color=PAL["green"])
    axes[1].set_ylabel("Cumulative gates"); axes[1].set_xlabel("Layer")
    axes[1].set_title("Cumulative Gate Count")
    plt.tight_layout()
    plt.savefig("fig4_depth_profile.png", bbox_inches="tight"); plt.show()

    # --- Fig 5 · angle distribution ------------------------------------------
    fig = plt.figure(figsize=(15, 5))
    fig.suptitle("Rotation Angle Distribution", fontweight="bold")
    ax1 = fig.add_subplot(1, 3, 1)
    ax1.hist(angles, bins=60, color=PAL["blue"], edgecolor="white", alpha=0.85)
    for pv in [0, PI/2, PI, 3*PI/2, 2*PI]:
        ax1.axvline(pv, color="red", ls="--", lw=0.9, alpha=0.6)
    ax1.set_xlabel("Angle (rad)"); ax1.set_ylabel("Frequency")
    ax1.set_title("All Rotation Angles")
    ax2 = fig.add_subplot(1, 3, 2, projection="polar")
    a2pi = angles % (2*PI)
    h, e = np.histogram(a2pi, bins=48, range=(0, 2*PI))
    ax2.bar(e[:-1], h, width=np.diff(e), alpha=0.75,
            color=PAL["orange"], edgecolor="white")
    ax2.set_title("Polar (mod 2π)", pad=12)
    ax3 = fig.add_subplot(1, 3, 3)
    if non_cliff:
        ax3.hist(non_cliff, bins=50, color=PAL["red"],
                 edgecolor="white", alpha=0.85)
        ax3.set_xlabel("Angle (rad)")
        ax3.set_title(f"Non-Clifford Angles  ({len(non_cliff)} total)")
    else:
        ax3.text(0.5, 0.5, "All angles are Clifford",
                 ha="center", va="center", transform=ax3.transAxes)
    plt.tight_layout()
    plt.savefig("fig5_angles.png", bbox_inches="tight"); plt.show()

    # --- Fig 6 · per-qubit load -----------------------------------------------
    fig, axes = plt.subplots(2, 1, figsize=(15, 8))
    fig.suptitle("Per-Qubit Gate Load", fontweight="bold")
    x = np.arange(num_qubits)
    axes[0].bar(x, g_load,  color=PAL["blue"],   alpha=0.85, label="Total")
    axes[0].bar(x, tq_load, color=PAL["red"],    alpha=0.85, label="2Q")
    axes[0].axhline(np.mean(g_load), color="black", ls="--", lw=1.2,
                    label=f"Mean ({np.mean(g_load):.1f})")
    axes[0].set_xticks(x); axes[0].set_xticklabels(range(num_qubits), fontsize=7)
    axes[0].set_ylabel("Gate count"); axes[0].legend()
    axes[0].set_title("Total & 2Q Gate Count per Qubit")
    axes[1].bar(x, tq_load, color=PAL["purple"], alpha=0.85)
    axes[1].axhline(np.mean(tq_load), color="black", ls="--", lw=1.2,
                    label=f"Mean 2Q ({np.mean(tq_load):.1f})")
    axes[1].set_xticks(x); axes[1].set_xticklabels(range(num_qubits), fontsize=7)
    axes[1].set_xlabel("Qubit index"); axes[1].set_ylabel("2Q gate count")
    axes[1].set_title("Two-Qubit Gate Load per Qubit")
    axes[1].legend()
    plt.tight_layout()
    plt.savefig("fig6_qubit_load.png", bbox_inches="tight"); plt.show()

    # --- Fig 7 · light cone --------------------------------------------------
    fig, ax = plt.subplots(figsize=(14, 4))
    ax.bar(range(num_qubits), cone_sizes, color=PAL["teal"], edgecolor="white")
    ax.axhline(num_qubits, color="red", ls="--", lw=1.2,
               label=f"Max ({num_qubits})")
    ax.axhline(avg_cone,   color="black", ls="-.", lw=1.2,
               label=f"Mean ({avg_cone:.1f})")
    ax.set_xlabel("Output qubit"); ax.set_ylabel("Light-cone size")
    ax.set_title("Backward Light-Cone Size per Output Qubit", fontweight="bold")
    ax.set_xticks(range(num_qubits))
    ax.set_xticklabels(range(num_qubits), fontsize=7)
    ax.legend()
    plt.tight_layout()
    plt.savefig("fig7_light_cone.png", bbox_inches="tight"); plt.show()

    # --- Fig 8 · entanglement proxy ------------------------------------------
    fig, axes = plt.subplots(1, 2, figsize=(15, 5))
    fig.suptitle("Entanglement Proxy  (Bipartition Sweep)", fontweight="bold")
    cuts = list(range(1, num_qubits))
    axes[0].fill_between(cuts, cross_counts, alpha=0.3, color=PAL["purple"])
    axes[0].plot(cuts, cross_counts, color=PAL["purple"], lw=1.5)
    axes[0].axvline(mid, color="red", ls="--", lw=1.2, label=f"Central cut ({mid})")
    axes[0].set_xlabel("Cut position"); axes[0].set_ylabel("Cross-boundary 2Q gates")
    axes[0].set_title("Cross-Boundary 2Q Gates"); axes[0].legend()
    ent_bounds = [min(c, min(cut, num_qubits-cut))*np.log(2)
                  for cut, c in zip(cuts, cross_counts)]
    axes[1].fill_between(cuts, ent_bounds, alpha=0.3, color=PAL["green"])
    axes[1].plot(cuts, ent_bounds, color=PAL["green"], lw=1.5)
    axes[1].axvline(mid, color="red", ls="--", lw=1.2)
    axes[1].set_xlabel("Cut position"); axes[1].set_ylabel("Entanglement UB (ebits)")
    axes[1].set_title("Entanglement Upper Bound per Cut")
    plt.tight_layout()
    plt.savefig("fig8_entanglement.png", bbox_inches="tight"); plt.show()

    # --- Fig 9 · dashboard ---------------------------------------------------
    fig = plt.figure(figsize=(18, 11))
    fig.patch.set_facecolor("#0d1117")
    gs9 = gridspec.GridSpec(3, 6, figure=fig, hspace=0.55, wspace=0.45)

    BLUE="#58a6ff"; GRN="#3fb950"; ORG="#d29922"
    RED="#f85149"; PUR="#bc8cff"; TEA="#39d353"

    kpi_box(fig.add_subplot(gs9[0,0]), num_qubits,    "Qubits",       "circuit width",    BLUE)
    kpi_box(fig.add_subplot(gs9[0,1]), depth,          "Depth",        "critical path",    GRN)
    kpi_box(fig.add_subplot(gs9[0,2]), total_g,        "Total Gates",  "all operations",   ORG)
    kpi_box(fig.add_subplot(gs9[0,3]), cx_count,       "CNOT Gates",   "CX ops",           RED)
    kpi_box(fig.add_subplot(gs9[0,4]), len(interact),  "Qubit Pairs",  "unique pairs",     PUR)
    kpi_box(fig.add_subplot(gs9[0,5]),
            f"{100*nc_frac:.0f}%",                     "Non-Clifford", "rotation angles",  TEA)

    def dark_ax(ax, title):
        ax.set_facecolor("#161b22")
        ax.set_title(title, color="white", fontsize=10)
        ax.tick_params(colors="#8b949e", labelsize=6)
        for sp in ax.spines.values(): sp.set_color("#30363d")

    ax_d = fig.add_subplot(gs9[1, :3])
    dark_ax(ax_d, "Gates per Layer")
    ax_d.bar(layers, g_1q, color=BLUE, alpha=0.85, label="1Q")
    ax_d.bar(layers, g_2q, bottom=g_1q, color=RED, alpha=0.85, label="2Q")
    ax_d.legend(fontsize=7, facecolor="#161b22", labelcolor="white")

    ax_q = fig.add_subplot(gs9[1, 3:])
    dark_ax(ax_q, "Per-Qubit Gate Load")
    ax_q.bar(range(num_qubits), g_load,  color=BLUE, alpha=0.8)
    ax_q.bar(range(num_qubits), tq_load, color=RED,  alpha=0.85)

    ax_bi = fig.add_subplot(gs9[2, :3])
    dark_ax(ax_bi, "Cross-Boundary 2Q Gates  (Entanglement Proxy)")
    ax_bi.fill_between(cuts, cross_counts, alpha=0.35, color=PUR)
    ax_bi.plot(cuts, cross_counts, color=PUR, lw=1.2)
    ax_bi.axvline(mid, color=RED, ls="--", lw=1.0)

    ax_lc = fig.add_subplot(gs9[2, 3:])
    dark_ax(ax_lc, "Backward Light-Cone Size")
    ax_lc.bar(range(num_qubits), cone_sizes, color=TEA, alpha=0.85)
    ax_lc.axhline(num_qubits, color=RED, ls="--", lw=1.0)

    fig.suptitle(f"⚛  QUANTUM PEAKED CIRCUIT · ANALYSIS DASHBOARD\n    {qasm_path}",
                 fontsize=14, fontweight="bold", color="white", y=1.01)
    plt.savefig("fig9_dashboard.png", bbox_inches="tight",
                facecolor="#0d1117", dpi=130)
    plt.show()

    # ── 9) Print report ────────────────────────────────────────────────────
    print("[9/9] Summary report …\n")
    anticonc_thresh = int(np.ceil(np.log2(num_qubits)))
    epsilon = 1e-3
    sk_d    = int(np.ceil(3.5 * np.log2(1/epsilon)))
    t_est   = len(non_cliff) * sk_d
    verdict = ("HIGHLY PEAKED — strong concentration expected"
               if two_q_depth > anticonc_thresh and richness > 0.3
               else "MODERATELY PEAKED — partial concentration expected")

    print("=" * 65)
    print(f"  ANALYSIS REPORT  ·  {qasm_path}")
    print("=" * 65)
    print(f"""
  STRUCTURAL
  ─────────────────────────────────────────────────────────
  Qubits (width)              : {num_qubits}
  Circuit depth               : {depth}
  Total gate count            : {total_g}
    Single-qubit gates        : {single_q}
    Two-qubit gates (raw)     : {raw_2q}  (CX={cx_count}, SWAP={swap_count})
  CNOT-equivalent total       : {cnot_equiv}
  Gate density (gates/D×W)    : {gate_density:.4f}
  Parallelism factor          : {total_g/depth:.2f}×

  CONNECTIVITY
  ─────────────────────────────────────────────────────────
  Unique interacting pairs    : {len(interact)}
  Max / avg qubit degree      : {max_deg} / {avg_deg:.2f}
  Graph diameter              : {diameter if diameter else '∞ (disconnected)'}
  Graph density               : {g_density:.4f}
  Avg clustering coefficient  : {clustering:.4f}

  ROTATION ANGLES
  ─────────────────────────────────────────────────────────
  Total rotation parameters   : {len(angles)}
  Clifford (π/2 multiples)    : {cliff_count}  ({100*(1-nc_frac):.1f}%)
  Non-Clifford                : {len(non_cliff)}  ({100*nc_frac:.1f}%)

  ENTANGLEMENT
  ─────────────────────────────────────────────────────────
  Central bipartition cross   : {cen_cross} 2Q gates
  Entanglement upper bound    : {ent_ub:.2f} ebits
  Richness score              : {richness:.3f}
  Avg light-cone coverage     : {avg_cone:.1f}/{num_qubits}  ({100*avg_cone/num_qubits:.0f}%)

  FAULT-TOLERANCE RESOURCES (ε = {epsilon})
  ─────────────────────────────────────────────────────────
  CNOT-equivalent gates       : {cnot_equiv}
  Non-Clifford rotations      : {len(non_cliff)}
  T-gate estimate (SK)        : ~{t_est:,}
  Two-qubit gate depth        : {two_q_depth}
  Circuit volume (D × W)      : {depth * num_qubits:,}

  PEAKED-CIRCUIT VERDICT
  ─────────────────────────────────────────────────────────
  Anti-conc. threshold        : {anticonc_thresh} 2Q-gate layers
  Measured 2Q depth           : {two_q_depth}
  → {verdict}

  Figures saved:
    fig1_gate_distribution.png   fig2_connectivity.png
    fig3_heatmap.png             fig4_depth_profile.png
    fig5_angles.png              fig6_qubit_load.png
    fig7_light_cone.png          fig8_entanglement.png
    fig9_dashboard.png
""")
    print(f"  ⏱  Total runtime: {time.time()-t0:.1f}s")
    print("=" * 65)


# ── run ────────────────────────────────────────────────────────────────────
run_analysis()