# -*- coding: utf-8 -*-
"""circuitAnalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDRbv5xSMXYB7NRo-ucuFt6WvavidFqo
"""

import time
import pyzx as zx
from qiskit import transpile, qasm2
from qiskit_aer import AerSimulator


def solve_obfuscated_circuit(fil):
    sta = time.time()

    qco = qasm2.load(
        fil,
        custom_instructions=qasm2.LEGACY_CUSTOM_INSTRUCTIONS
    )
    qas = qasm2.dumps(qco)

    try:
        pyc = zx.Circuit.from_qasm(qas)
        grf = pyc.to_graph()

        zx.clifford_simp(grf)

        rdc = zx.extract_circuit(grf)
        rqs = rdc.to_qasm()

    except Exception:
        rqs = qas

    qcr = qasm2.loads(
        rqs,
        custom_instructions=qasm2.LEGACY_CUSTOM_INSTRUCTIONS
    )

    if not qcr.cregs:
        qcr.measure_all()

    qop = transpile(
        qcr,
        optimization_level=3
    )

    aer = AerSimulator(
        method="matrix_product_state",
        matrix_product_state_max_bond_dimension=128
    )

    cnt = (
        aer.run(qop, shots=1024)
        .result()
        .get_counts()
    )

    dom = max(
        cnt.items(),
        key=lambda x: x[1]
    )

    bit = dom[0]
    con = dom[1] / 1024 * 100

    print(f"Bitstring: {bit}")
    print(f"Confidence: {con:.2f}%")
    print(f"Time: {time.time() - sta:.2f}s")


if __name__ == "__main__":
    solve_obfuscated_circuit("challenge-48_36.txt")