# -*- coding: utf-8 -*-
"""distillation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smKnbgCtbuE4SeU5Jf-sToeOWw8ONoQL
"""

!pip install qiskit quimb qiskit-quimb torch numpy

import numpy as np
import torch
from collections import Counter
from qiskit import QuantumCircuit
import quimb
from qiskit_quimb import quimb_circuit

# 1. Load the circuit
filename = "36.qasm"
circuit = QuantumCircuit.from_qasm_file(filename)

print(f"Loaded {filename}")
print(f"Qubits: {circuit.num_qubits}")
print(f"Operations: {circuit.count_ops()}\n")

# 2. Setup GPU backend
def to_backend(x):
    return torch.tensor(x, dtype=torch.complex64, device="cuda")

# 3. Run MPS simulation
print("Running MPS Simulation (NumPy/CPU)...")
q_circuit = quimb_circuit(
    circuit,
    quimb_circuit_class=quimb.tensor.CircuitPermMPS,
    # to_backend=to_backend,  <-- DELETE THIS LINE
    max_bond=128,
    cutoff=1e-12,
    progbar=True
)

# 4. Undo the qubit permutation
qubit_mapping = list(range(q_circuit.N))
qubit_mapping = [q_circuit.qubits.index(q) for q in range(q_circuit.N)]
qubit_mapping = [qubit_mapping[q] for q in qubit_mapping]

# 5. Generate samples
print("\nGenerating 1000 samples...")
samples = [''.join(bs[q] for q in qubit_mapping) for bs in q_circuit.sample(4096, seed=1234)]
csamples = Counter(samples)

print("\nTop 5 raw samples:")
for bitstring, count in csamples.most_common(5):
    print(f"{bitstring}: {count}")

# 6. Distill peak bitstring via majority voting
bit_probs = np.array([[int(s) for s in ss] for ss in samples]).mean(axis=0)

# Notice the [::-1] at the exact end!
voted_bitstring = "".join(str(i) for i in (bit_probs > 0.5).astype(int).tolist())[::-1]

print("\n" + "="*50)
print(f"Distilled Peak Bitstring: {voted_bitstring}")
print(f"Found in raw samples? {voted_bitstring in csamples}")
print("="*50)