# -*- coding: utf-8 -*-
"""hard_template_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OB5cRAeEZZ-mHMTM-QHZeyk4Hz9339Uz
"""

"""
peak_solver.py — Recover the secret bitstring of a "peaked" quantum circuit.

Background
----------
Each challenge circuit C, fed |0...0>, outputs one bitstring x with much higher
probability than anything else. The ideal construction is

        C = U1 U1+ . P1 . U2 U2+ . P2 . U3 U3+

where every Ui Ui+ pair is the identity, so the ideal unitary collapses to a
tensor product of single-qubit X-rotations by 0 or pi. That means C|0> is a
product basis state and each output bit is fixed *independently*:

        x_i = 0  if  <0| C+ Z_i C |0>  > 0
        x_i = 1  if  <0| C+ Z_i C |0>  < 0

The circuit is then obfuscated (spreading + a few non-unitary edits), so we
cannot read x off any single gate. We instead compute each <Z_i> directly by
Heisenberg (Pauli) back-propagation: push Z_i backwards through the reversed
gate list, conjugating it gate by gate, and keep the Pauli sum sparse with
magnitude-based truncation. Because the obfuscator's spreading has to un-spread
to leave a product state, the operator stays sparse and every <Z_i> converges
to a clear sign.

Representation
--------------
A Pauli term is (x_mask, z_mask, coeff) where x_mask / z_mask are bitmasks over
the qubits (<= 64 qubits fits in one uint64) and coeff is a real number. The
single-qubit Pauli on qubit q is read from bit q of each mask:

        (x,z) = (0,0)->I   (1,0)->X   (1,1)->Y   (0,1)->Z

These are the Hermitian Paulis, so all coefficients stay real throughout.

Conjugation rules (backwards: O -> G+ O G)
------------------------------------------
RZ(t):  X -> cos t X - sin t Y       (generator Z; touches terms with x-bit=1)
        Y -> sin t X + cos t Y
RX(t):  Y -> cos t Y - sin t Z       (generator X; touches terms with z-bit=1)
        Z -> sin t Y + cos t Z
CX:     Clifford permutation of Paulis (no branching). Mask update
        x_t ^= x_c ; z_c ^= z_t, plus a +/-1 sign read from a table that is
        generated from the 2-qubit matrices at startup (so it is verifiable).

Usage
-----
    python3 peak_solver.py circuit.qasm                  # solve all qubits
    python3 peak_solver.py circuit.qasm --qubits 5 6 37  # solve a subset
    python3 peak_solver.py circuit.qasm -K 150000        # bigger Pauli budget
    python3 peak_solver.py circuit.qasm --recheck 5 37   # high-budget re-solve

Output is the bitstring with qubit 0 as the right-most bit, plus the per-qubit
expectation values (their magnitude is a confidence signal).
"""

import argparse
import math
import re
import time

import numpy as np

U64 = np.uint64


# --------------------------------------------------------------------------- #
# Parsing
# --------------------------------------------------------------------------- #
def parse_angle(expr: str) -> float:
    """Evaluate a QASM angle expression such as '3*pi/4' or '-1.0793'."""
    expr = expr.strip().replace("pi", f"({math.pi})")
    return float(eval(expr, {"__builtins__": {}}, {}))


def load_circuit(path: str):
    """Return (n_qubits, gates). Gates are ('rz'|'rx', q, theta) or ('cx', c, t)."""
    n_qubits, gates = 0, []
    rot_re = re.compile(r"(rz|rx)\(([^)]+)\)\s*q\[(\d+)\]")
    cx_re = re.compile(r"cx\s*q\[(\d+)\]\s*,\s*q\[(\d+)\]")
    for line in open(path):
        line = line.strip()
        if not line or line.startswith(("OPENQASM", "include")):
            continue
        if line.startswith("qreg"):
            n_qubits = int(re.search(r"\[(\d+)\]", line).group(1))
            continue
        m = rot_re.match(line)
        if m:
            gates.append((m.group(1), int(m.group(3)), parse_angle(m.group(2))))
            continue
        m = cx_re.match(line)
        if m:
            gates.append(("cx", int(m.group(1)), int(m.group(2))))
            continue
        if not line.startswith(("measure", "barrier", "creg")):
            raise ValueError(f"Unparsed line: {line}")
    return n_qubits, gates


# --------------------------------------------------------------------------- #
# CX sign table (generated from matrices so it is provably correct)
# --------------------------------------------------------------------------- #
def build_cx_sign_table() -> np.ndarray:
    """sign_flat[xc + 2*zc + 4*xt + 8*zt] = +/-1 for CX conjugation."""
    I2 = np.eye(2, dtype=complex)
    X = np.array([[0, 1], [1, 0]], complex)
    Y = np.array([[0, -1j], [1j, 0]], complex)
    Z = np.array([[1, 0], [0, -1]], complex)
    P = [I2, X, Y, Z]
    b2p = {(0, 0): 0, (1, 0): 1, (1, 1): 2, (0, 1): 3}  # (x,z) -> Pauli index
    CNOT = np.array([[1, 0, 0, 0], [0, 1, 0, 0],
                     [0, 0, 0, 1], [0, 0, 1, 0]], complex)
    table = np.zeros(16)
    for xc in (0, 1):
        for zc in (0, 1):
            for xt in (0, 1):
                for zt in (0, 1):
                    p_in = np.kron(P[b2p[(xc, zc)]], P[b2p[(xt, zt)]])
                    p_out = CNOT @ p_in @ CNOT
                    # Output Paulis follow the mask rule; recover only the sign.
                    ref = np.kron(P[b2p[(xc, zc ^ zt)]], P[b2p[(xt ^ xc, zt)]])
                    s = np.real(np.trace(p_out @ ref)) / 4.0
                    assert abs(abs(s) - 1) < 1e-9, (xc, zc, xt, zt, s)
                    table[xc + 2 * zc + 4 * xt + 8 * zt] = round(s)
    # Spot-check: Y_c (x) Y_t  ->  -X_c (x) Z_t
    assert table[1 + 2 + 4 + 8] == -1
    return table


SIGN_FLAT = build_cx_sign_table()


# --------------------------------------------------------------------------- #
# Core back-propagation
# --------------------------------------------------------------------------- #
def _snap(v: float) -> float:
    """Snap near-integers so Clifford angles stay exact (no spurious terms)."""
    for t in (-1.0, 0.0, 1.0):
        if abs(v - t) < 1e-9:
            return t
    return v


def _merge_prune(xm, zm, co, thr, K):
    """Combine identical Paulis, drop tiny coeffs, keep the top-K by magnitude."""
    n = len(xm)
    if n == 0:
        return xm, zm, co
    order = np.lexsort((zm, xm))
    xm, zm, co = xm[order], zm[order], co[order]
    starts = np.ones(n, bool)
    starts[1:] = ~((xm[1:] == xm[:-1]) & (zm[1:] == zm[:-1]))
    grp = np.cumsum(starts) - 1
    coeffs = np.bincount(grp, weights=co, minlength=int(grp[-1]) + 1)
    xm, zm = xm[starts], zm[starts]
    keep = np.abs(coeffs) > thr
    xm, zm, coeffs = xm[keep], zm[keep], coeffs[keep]
    if len(coeffs) > K:
        idx = np.argpartition(np.abs(coeffs), len(coeffs) - K)[len(coeffs) - K:]
        xm, zm, coeffs = xm[idx], zm[idx], coeffs[idx]
    return xm, zm, coeffs


def _apply_cx(c, t, xm, zm, co):
    c, t, one = U64(c), U64(t), U64(1)
    xc = (xm >> c) & one
    zc = (zm >> c) & one
    xt = (xm >> t) & one
    zt = (zm >> t) & one
    idx = (xc + (zc << one) + (xt << U64(2)) + (zt << U64(3))).astype(np.int64)
    co = co * SIGN_FLAT[idx]
    return xm ^ (xc << t), zm ^ (zt << c), co


def _apply_rot(kind, q, theta, xm, zm, co, thr, K):
    c, s = _snap(math.cos(theta)), _snap(math.sin(theta))
    q, one = U64(q), U64(1)
    # A term is affected iff its single-qubit Pauli anticommutes with the
    # rotation generator: x-bit for RZ (generator Z), z-bit for RX (generator X).
    anti = ((xm >> q) & one == one) if kind == "rz" else ((zm >> q) & one == one)
    co_scaled = np.where(anti, co * c, co)          # cos branch (and untouched terms)
    if s != 0.0:                                     # sin branch -> partner Paulis
        sel = anti
        pxm, pzm = xm[sel].copy(), zm[sel].copy()
        if kind == "rz":                            # X<->Y: flip z-bit
            pzm ^= (one << q)
            psign = np.where(((zm[sel] >> q) & one) == one, 1.0, -1.0)
        else:                                       # Y<->Z: flip x-bit
            pxm ^= (one << q)
            psign = np.where(((xm[sel] >> q) & one) == one, -1.0, 1.0)
        pco = co[sel] * s * psign
        xm = np.concatenate([xm, pxm])
        zm = np.concatenate([zm, pzm])
        co_scaled = np.concatenate([co_scaled, pco])
    return _merge_prune(xm, zm, co_scaled, thr, K)


def expval_z(gates, qubit, thr=1e-7, K=40000):
    """Return <0| C+ Z_qubit C |0> via Heisenberg back-propagation."""
    xm = np.array([0], U64)
    zm = np.array([1 << qubit], U64)
    co = np.array([1.0])
    one = U64(1)
    for kind, a, b in reversed(gates):
        if kind == "cx":
            # Skip if the operator is trivial on both wires (cheap light-cone gate).
            if not (((xm >> U64(a)) & one).any() or ((zm >> U64(b)) & one).any()):
                continue
            xm, zm, co = _apply_cx(a, b, xm, zm, co)
        else:
            if kind == "rz" and not ((xm >> U64(a)) & one).any():
                continue
            if kind == "rx" and not ((zm >> U64(a)) & one).any():
                continue
            xm, zm, co = _apply_rot(kind, a, b, xm, zm, co, thr, K)
    # |0> is a +1 eigenstate of every I/Z string; X/Y strings vanish.
    return float(co[xm == 0].sum())


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #
def solve(gates, n_qubits, qubits, thr, K, verbose=True):
    evs = {}
    for i in qubits:
        t0 = time.time()
        ev = expval_z(gates, i, thr, K)
        evs[i] = ev
        if verbose:
            flag = "  <-- marginal" if abs(ev) < 0.10 else ""
            print(f"  q{i:>2}  <Z>={ev:+.4f}  bit={0 if ev > 0 else 1}"
                  f"  ({time.time() - t0:.1f}s){flag}", flush=True)
    return evs


def bitstring(evs, n_qubits):
    """Assemble the bitstring with qubit 0 as the right-most character."""
    bits = ["?"] * n_qubits
    for i, ev in evs.items():
        bits[i] = "1" if ev < 0 else "0"
    return "".join(bits[i] for i in range(n_qubits - 1, -1, -1))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("qasm", help="path to the .qasm circuit")
    ap.add_argument("--qubits", type=int, nargs="+",
                    help="subset of qubits to solve (default: all)")
    ap.add_argument("--recheck", type=int, nargs="+",
                    help="re-solve these qubits at the high budget below")
    ap.add_argument("-K", type=int, default=40000, help="max Pauli terms kept")
    ap.add_argument("--thr", type=float, default=1e-7, help="coeff prune threshold")
    ap.add_argument("--recheck-K", type=int, default=200000,
                    help="Pauli budget used by --recheck")
    args = ap.parse_args()

    n_qubits, gates = load_circuit(args.qasm)
    n_cx = sum(g[0] == "cx" for g in gates)
    print(f"Loaded {args.qasm}: {n_qubits} qubits, {len(gates)} gates "
          f"({n_cx} CX), budget K={args.K}\n")

    if args.recheck:
        print(f"High-budget recheck (K={args.recheck_K}):")
        evs = solve(gates, n_qubits, args.recheck, args.thr, args.recheck_K)
        return

    targets = args.qubits if args.qubits else list(range(n_qubits))
    evs = solve(gates, n_qubits, targets, args.thr, args.K)

    if len(targets) == n_qubits:
        bs = bitstring(evs, n_qubits)
        marg = [i for i, v in evs.items() if abs(v) < 0.10]
        print(f"\nbitstring (q{n_qubits - 1}...q0):\n{bs}")
        if marg:
            print(f"\nMarginal qubits (|<Z>|<0.10), recommend --recheck: "
                  f"{sorted(marg)}")


if __name__ == "__main__":
    main()