# -*- coding: utf-8 -*-
"""36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLaHG4SpHfj_XabLX8jfawHakOzSqpat
"""

import re, math, numpy as np, json

PI = math.pi
_ang_re = re.compile(r'^(rz|rx)\(([^)]+)\)\s*q\[(\d+)\];')
_cx_re  = re.compile(r'^cx\s*q\[(\d+)\],\s*q\[(\d+)\];')
_sw_re  = re.compile(r'^swap\s*q\[(\d+)\],\s*q\[(\d+)\];')

def parse(path):
    gates = []  # (kind, a, b)  kind in {'rz','rx','cx'}; for rot a=qubit,b=angle; for cx a=ctrl,b=tgt
    with open(path) as f:
        for line in f:
            line = line.strip()
            m = _ang_re.match(line)
            if m:
                kind, expr, q = m.group(1), m.group(2), int(m.group(3))
                expr = expr.replace('pi', '('+repr(PI)+')')
                ang = eval(expr, {"__builtins__": {}}, {})
                gates.append((kind, q, float(ang)))
                continue
            m = _cx_re.match(line)
            if m:
                gates.append(('cx', int(m.group(1)), int(m.group(2))))
                continue
            m = _sw_re.match(line)
            if m:
                gates.append(('swap', int(m.group(1)), int(m.group(2))))
    return gates

def nonclifford_count(gates):
    n = 0
    for k,a,b in gates:
        if k in ('rz','rx'):
            # branching iff both cos and sin nonzero (i.e. angle not a multiple of pi/2)
            if abs(math.sin(b)) > 1e-9 and abs(math.cos(b)) > 1e-9:
                n += 1
    return n

def light_cone(gates, target_q):
    """Return reversed sublist of gates in the backward light cone of Z_{target_q}."""
    active = {target_q}
    cone_rev = []
    for g in reversed(gates):
        k = g[0]
        if k == 'cx':
            c, t = g[1], g[2]
            if c in active or t in active:
                active.add(c); active.add(t)
                cone_rev.append(g)
        elif k == 'swap':
            a, b = g[1], g[2]
            if a in active or b in active:
                active.add(a); active.add(b)
                cone_rev.append(g)
        else:  # rotation on g[1]
            if g[1] in active:
                cone_rev.append(g)
    return cone_rev  # already in reverse-of-circuit order

def merge_prune(x, z, c, thr, K):
    order = np.lexsort((z, x))
    xs = x[order]; zs = z[order]; cs = c[order]
    # group boundaries where (x,z) changes
    if len(xs) == 0:
        return xs, zs, cs
    new = np.empty(len(xs), dtype=bool)
    new[0] = True
    np.not_equal(xs[1:], xs[:-1], out=new[1:])
    new[1:] |= (zs[1:] != zs[:-1])
    starts = np.nonzero(new)[0]
    cc = np.add.reduceat(cs, starts)
    ux = xs[starts]; uz = zs[starts]
    keep = np.abs(cc) > thr
    ux, uz, cc = ux[keep], uz[keep], cc[keep]
    if len(cc) > K:
        idx = np.argpartition(np.abs(cc), len(cc) - K)[-K:]
        ux, uz, cc = ux[idx], uz[idx], cc[idx]
    return ux, uz, cc

def solve_qubit(target_q, thr=1e-7, K=40000, gates=None):
    cone_rev = light_cone(gates, target_q)
    # initial operator: Z on target_q  -> x=0, z=bit(target_q)
    x = np.array([np.uint64(0)], dtype=np.uint64)
    z = np.array([np.uint64(1) << np.uint64(target_q)], dtype=np.uint64)
    c = np.array([1.0], dtype=np.float64)

    for g in cone_rev:
        k = g[0]
        if k == 'cx':
            ctrl, tgt = g[1], g[2]
            bc = np.uint64(1) << np.uint64(ctrl)
            bt = np.uint64(1) << np.uint64(tgt)
            xc = ((x & bc) != 0)
            zc = ((z & bc) != 0)
            xt = ((x & bt) != 0)
            zt = ((z & bt) != 0)
            # sign = (-1)^( xc & zt & (xt ^ zc ^ 1) )
            flip = xc & zt & (xt ^ zc ^ True)
            c = np.where(flip, -c, c)
            # masks: x_t ^= x_c ; z_c ^= z_t
            x = np.where(xc, x ^ bt, x)
            z = np.where(zt, z ^ bc, z)
        elif k == 'swap':
            a, b = np.uint64(g[1]), np.uint64(g[2])
            one = np.uint64(1)
            dx = ((x >> a) ^ (x >> b)) & one
            x = x ^ ((dx << a) | (dx << b))
            dz = ((z >> a) ^ (z >> b)) & one
            z = z ^ ((dz << a) | (dz << b))
        else:
            q = g[1]; ang = g[2]
            ct = math.cos(ang); st = math.sin(ang)
            bq = np.uint64(1) << np.uint64(q)
            sin0 = abs(st) < 1e-12
            cos0 = abs(ct) < 1e-12
            if k == 'rz':
                aff = (x & bq) != 0   # X or Y on q
                if sin0:              # angle ~ 0 or pi: sign only
                    if ct < 0:
                        c = np.where(aff, c * ct, c)
                    continue
                if cos0:              # angle ~ +/-pi/2: bijective relabel, no growth
                    zq = (z & bq) != 0
                    c = np.where(aff, c * st * (2.0 * zq - 1.0), c)
                    z = np.where(aff, z ^ bq, z)
                    continue
                zq = ((z & bq) != 0)[aff]
                bx_x, bx_z, bx_c = x[aff], z[aff] ^ bq, c[aff] * st * (2.0 * zq - 1.0)
                c = np.where(aff, c * ct, c)
                x = np.concatenate([x, bx_x]); z = np.concatenate([z, bx_z]); c = np.concatenate([c, bx_c])
            else:  # rx
                aff = (z & bq) != 0   # Z or Y on q
                if sin0:
                    if ct < 0:
                        c = np.where(aff, c * ct, c)
                    continue
                if cos0:
                    xq = (x & bq) != 0
                    c = np.where(aff, c * st * (1.0 - 2.0 * xq), c)
                    x = np.where(aff, x ^ bq, x)
                    continue
                xq = ((x & bq) != 0)[aff]
                bx_x, bx_z, bx_c = x[aff] ^ bq, z[aff], c[aff] * st * (1.0 - 2.0 * xq)
                c = np.where(aff, c * ct, c)
                x = np.concatenate([x, bx_x]); z = np.concatenate([z, bx_z]); c = np.concatenate([c, bx_c])
            x, z, c = merge_prune(x, z, c, thr, K)

    # readout: sum coeff over pure I/Z terms (x==0)
    val = float(c[x == np.uint64(0)].sum())
    return val, len(c)

if __name__ == '__main__':
    import sys, time
    gates = parse('/mnt/user-data/uploads/38.qasm')
    print('gates total', len(gates),
          'cx', sum(1 for g in gates if g[0]=='cx'),
          'rot', sum(1 for g in gates if g[0]!='cx'),
          'nonclifford', nonclifford_count(gates))