# -*- coding: utf-8 -*-
"""Pyzx implementation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Of8NFTBRi5lmZ2asfYJL6mHx5bPCvjbn
"""

!pip install -q qiskit qiskit-aer
!pip -q install pyzx networkx qiskit

import pyzx as zx
import networkx as nx
from collections import Counter
import os

# Load circuit
QASM_FILE = "challenge-64_25.qasm"

print("Loading circuit...")
circ = zx.Circuit.load(QASM_FILE)

print("\nCircuit loaded.")
print("Qubits:", circ.qubits)
print("Gates :", len(circ.gates))

# Original gate counts
gate_counter = Counter()

for g in circ.gates:
    gate_counter[type(g).__name__] += 1

print("\n===== ORIGINAL GATE COUNTS =====")
for k, v in sorted(gate_counter.items()):
    print(f"{k:20s} {v}")

# Build interaction graph
G = nx.Graph()

for q in range(circ.qubits):
    G.add_node(q)

for g in circ.gates:

    name = type(g).__name__.lower()

    if "cnot" in name or "cx" in name:

        try:
            G.add_edge(g.control, g.target)
        except:
            pass

    elif hasattr(g, "control") and hasattr(g, "target"):
        G.add_edge(g.control, g.target)

# Connectivity analysis
components = list(nx.connected_components(G))

print("\n===== CONNECTIVITY =====")
print("Connected Components:", len(components))

sizes = sorted([len(c) for c in components], reverse=True)
print("Component sizes:", sizes)

try:
    tw, decomp = nx.approximation.treewidth_min_fill_in(G)

    print("\n===== TREEWIDTH =====")
    print("Approximate Treewidth:", tw)

except Exception as e:
    print("\nTreewidth estimation failed:", e)

# ZX reduction
print("\nConverting to ZX graph...")

g = circ.to_graph()

print("Before reduction")
print("Vertices:", g.num_vertices())
print("Edges:", g.num_edges())

zx.simplify.full_reduce(g)

print("\nAfter reduction")
print("Vertices:", g.num_vertices())
print("Edges:", g.num_edges())

try:
    print("Graph-like:", zx.simplify.is_graph_like(g))
except Exception as e:
    print("is_graph_like failed:", e)

try:
    zx.simplify.to_graph_like(g)
    print("Converted to graph-like")
except Exception as e:
    print("to_graph_like failed:", e)

try:
    optimized = zx.extract_circuit(g)
    print("Extraction successful")
except Exception as e:
    print("Extraction failed:")
    print(type(e))
    print(e)

print("Vertices:", g.num_vertices())
print("Edges   :", g.num_edges())

print("\n===== RUNNING FULL REDUCE =====")

zx.simplify.full_reduce(g)

print("Reduction complete.")
print("Reduced graph vertices:", g.num_vertices())
print("Reduced graph edges   :", g.num_edges())

# Extract optimized circuit
print("\nExtracting optimized circuit...")

optimized = zx.extract_circuit(g)

print("Done.")

optimized = optimized.to_basic_gates()

try:
    optimized = optimized.split_phase_gates()
except:
    pass

# Compare results
orig_gates = len(circ.gates)
new_gates = len(optimized.gates)

print("\n==============================")
print("RESULTS")
print("==============================")

print("Original gates :", orig_gates)
print("Reduced gates  :", new_gates)

if orig_gates > 0:
    reduction = 100 * (orig_gates - new_gates) / orig_gates
    print(f"Reduction      : {reduction:.2f}%")

new_counter = Counter()

for gate in optimized.gates:
    new_counter[type(gate).__name__] += 1

print("\n===== OPTIMIZED GATE COUNTS =====")

for k, v in sorted(new_counter.items()):
    print(f"{k:20s} {v}")

def count_cx(circuit):

    total = 0

    for gate in circuit.gates:

        name = type(gate).__name__.lower()

        if "cnot" in name or "cx" in name:
            total += 1

    return total

print("\n===== CX COMPARISON =====")
print("Original CX :", count_cx(circ))
print("Reduced  CX :", count_cx(optimized))

# Save output
OUTPUT_QASM = "optimized.qasm"

qasm_text = optimized.to_qasm()

with open(OUTPUT_QASM, "w") as f:
    f.write(qasm_text)

print("\nSaved:", OUTPUT_QASM)

# Alternative reductions
print("\n===== TELEPORT REDUCE TEST =====")

g2 = circ.to_graph()

zx.simplify.teleport_reduce(g2)

teleported = zx.extract_circuit(g2)

print("Teleport-reduced gates:", len(teleported.gates))

print("\n===== CLIFFORD SIMP TEST =====")

g3 = circ.to_graph()

zx.simplify.clifford_simp(g3)

clifford = zx.extract_circuit(g3)

print("Clifford-simp gates:", len(clifford.gates))

print("\nFinished.")