# -*- coding: utf-8 -*-
"""Unswapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbAmekqe2Ib7KbOT9bQEtSO9d-A7iac6
"""

!pip install qiskit quimb qiskit-quimb torch numpy pandas matplotlib cotengra optuna

import warnings
warnings.filterwarnings('ignore', category=UserWarning, module='autoray')

import time
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

from qiskit import QuantumCircuit
from qiskit.transpiler.passes import Collect2qBlocks, ConsolidateBlocks
from qiskit.transpiler import PassManager

# Import custom methods from the repository (requires unswap.py and utils.py in Colab)
from utils import to_backend_cuda
from unswap import mpo_compress_unswap, mpo_to_mps

t0 = time.perf_counter()

# 1. Load circuit and collect 2q gate blocks
filename = "compressed_moderate_32.qasm"
print(f"Loading {filename}...")
circuit = QuantumCircuit.from_qasm_file(filename)

collect_2q = PassManager([Collect2qBlocks(), ConsolidateBlocks(force_consolidate=True)])
circuit = collect_2q.run(circuit)
print(f"Operations after consolidation: {circuit.count_ops()}\n")

# 2. Compress circuit core using Unswapping
print("Starting MPO Compression and Unswapping (This may take a while)...")
mpo, layers_left, layers_right, stats_data = mpo_compress_unswap(
    circuit,
    seed=123,
    to_backend=to_backend_cuda,
    cutoff=0.002,
    max_bond=8192,
    unswap_threshold=1e6,
    center_ratio=0.5,
    equal=False,
    flip_freq=None,
    max_its=20,
    early_stopping_gates=0,
    hows=("both", "left", "right")
)

# 3. Simulate remaining circuit with MPS
print("\nConverting Core MPO back to MPS...")
mps, perm = mpo_to_mps(
    mpo,
    layers_left[:-2],
    layers_right,
    cutoff=0.002,
    to_backend=to_backend_cuda
)

# 4. Sample from the MPS to extract bitstring
print("\nSampling MPS...")
raw_samples = [p for p, _ in list(mps.sample(1000))]
samples = ["".join(str(b) for b in bs) for bs in raw_samples]

csamples = Counter(samples)
pred_bs = csamples.most_common()[0][0]

# Account for the qubit permutation map
perm_pred_bs = "".join([pred_bs[i] for i in perm])

print("\n" + "="*50)
print(f"Unswapped Peak Bitstring: {perm_pred_bs}")
print("="*50 + "\n")

# 5. Process plotting statistics
u_stats = {"u_consumed_total": 0, "u_consumed_total_left": 0, "u_consumed_total_right": 0}
for i in range(len(stats_data)):
    if stats_data[i]["stage"] == "absorbing":
        u_stats = {k: stats_data[i][k] for k in u_stats.keys()}
    else:
        stats_data[i].update(u_stats)

df = pd.DataFrame(stats_data)
df_absorb = df[df["stage"] == "absorbing"]
df_unswap = df[df["stage"] == "unswapping"]

# Save stats
csv_name = filename.replace(".qasm", "_unswapping_stats.csv")
df.to_csv(csv_name)
print(f"Saved run statistics to {csv_name}")

# 6. Plot simulation progress
plt.figure(figsize=(15, 6))

# Plot 1: Total Elements vs Unitaries Consumed
plt.subplot(2, 1, 1)
plt.plot(df["u_consumed_total"].values, df["total_elems"].values, '-', color='lightgray', linewidth=2.0, label="Timeline")
plt.plot(df_unswap["u_consumed_total"].values, df_unswap["total_elems"].values, '.r', markersize=4, label="Unswapping")
plt.plot(df_absorb["u_consumed_total"].values, df_absorb["total_elems"].values, '.b', markersize=4, label="Absorption")
plt.yscale('log')
plt.xlabel("Total 2q Unitaries Consumed")
plt.ylabel("Total tensor elements")
plt.legend()

# Plot 2: Total Elements vs Time
plt.subplot(2, 1, 2)
plt.plot(df["time"].values, df["total_elems"].values, '-', color='lightgray', linewidth=2.0, label="Timeline")
plt.plot(df_unswap["time"].values, df_unswap["total_elems"].values, '.r', markersize=4, label="Unswapping")
plt.plot(df_absorb["time"].values, df_absorb["total_elems"].values, '.b', markersize=4, label="Absorption")
plt.yscale('log')
plt.xlabel("Time (seconds)")
plt.ylabel("Total tensor elements")
plt.legend()

plt.tight_layout()
plt.show()

total_time = time.perf_counter() - t0
print(f"\nTotal execution time: {total_time:.2f}s")